fix: add release automation (#7)
Signed-off-by: matttrach <matt.trachier@suse.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -17,8 +17,9 @@ jobs:
         id: release-please
         with:
           release-type: go
+      # These run only if a release PR was opened or modified, so not when the PR is merged
       - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1 https://github.com/actions/github-script/commits/main
-        if: steps.release-please.outputs.pr
+        if: steps.release-please.outputs.prs_created
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
           script: |
@@ -29,15 +30,58 @@ jobs:
               body: "Please make sure e2e tests pass before merging this PR! \n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
             })
       - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
+        if: steps.release-please.outputs.prs_created
         with:
           go-version-file: 'go.mod'
           cache: true
       - name: run_unit_tests
+        if: steps.release-please.outputs.prs_created
         run: make test
       - name: run_acc_tests
+        if: steps.release-please.outputs.prs_created
         run: make testacc
-      - name: Import GPG key
-        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
-        id: import_gpg
+      # These run after release-please generates a release, so when the release PR is merged
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        if: steps.release-please.outputs.releases_created
         with:
-          gpg_private_key: ${{ secrets.GPG_KEY }}
+          fetch-depth: 0
+      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
+        if: steps.release-please.outputs.releases_created
+        with:
+          go-version-file: 'go.mod'
+          cache: true
+      - name: import_gpg_key
+        id: import_gpg_key
+        env:
+          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
+          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
+          GPG_KEY: ${{ secrets.GPG_KEY }}
+        run: |
+          cleanup() {
+            # clear history just in case
+            history -c
+          }
+          trap cleanup EXIT TERM
+
+          # sanitize variables
+          GPG_PASSPHRASE="$(echo "${GPG_PASSPHRASE}" | xargs)"
+          GPG_KEY_ID="$(echo "${GPG_KEY_ID}" | xargs)"
+          GPG_KEY="$(echo -n "${GPG_KEY}" | awk '/-----BEGIN PGP PRIVATE KEY BLOCK-----/,/-----END PGP PRIVATE KEY BLOCK-----/')"
+
+          if [ -z "${GPG_PASSPHRASE}" ]; then echo "gpg passphrase empty"; exit 1; fi
+          if [ -z "${GPG_KEY_ID}" ]; then echo "key id empty"; exit 1; fi
+          if [ -z "${GPG_KEY}" ]; then echo "key contents empty"; exit 1; fi
+
+          echo "Importing gpg key"
+          echo "${GPG_KEY}" | gpg --import --batch > /dev/null || { echo "Failed to import GPG key"; exit 1; }
+          FINGERPRINT="$(gpg --list-secret-keys --with-colons "${GPG_KEY_ID}" | grep fpr | cut -d: -f10)"
+          echo "fingerprint=$FINGERPRINT" >> "$GITHUB_OUTPUT"
+      - name: Run GoReleaser
+        if: steps.release-please.outputs.releases_created
+        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
+        with:
+          args: release --clean
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GPG_FINGERPRINT: ${{ steps.import_gpg_key.outputs.fingerprint }}
+          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
